.TH bcron-sched 8
.SH NAME
bcron-sched \- bcron system scheduler
.SH SYNOPSIS
.B bcron-sched
.SH DESCRIPTION
.B bcron-sched
reads job descriptions from stored crontabs, determines when they need
to be run, and writes execution commands to standard output for
.B bcron-exec
to execute.
.P
.B bcron-sched
should normally be run by
.B bcron-start
in conjunction with
.BR bcron-exec .
.SH SIGNALS
.TP 5
.B SIGUSR1
On receipt of the
.B SIGUSR1
signal,
.B bcron-sched
will dump a set of log messages describing all the jobs it is scheduling.
.SH ENVIRONMENT
.TP 5
.B BCRON_SPOOL
The spool directory for bcron.  Defaults to
.IR /var/spool/cron .
.SH FILES
.I /var/spool/cron/crontabs/crontabs

.I /var/spool/cron/crontabs/trigger
.SH SEE ALSO
bcron-exec(8), bcron-start(8), bcrontab(1)
.SH AUTHOR
Bruce Guenter <bruce@untroubled.org>
